---
openapi: 3.0.1
info:
  title: 
  version: v1
paths:
  "/api/v1/doctors":
    get:
      summary: list doctors
      responses:
        '200':
          description: successful
  "api/v1/doctor/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show doctor
      responses:
        '200':
          description: successful
    delete:
      summary: delete doctor
      responses:
        '200':
          description: successful
  "/api/v1/doctors":
    post:
      summary: create doctor
      responses:
        '200':
          description: successful
  "/api/v1/reservations/{user_id}":
     - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: reserve doctor
      responses:
        '200':
          description: successful
  "/api/v1/register/{username}/{name}/{email}":
    parameters:
    - name: username
      in: path
      description: username
      required: true
      schema:
        type: string
    - name: name
      in: path
      description: name
      required: true
      schema:
        type: string
    - name: email
      in: path
      description: email
      required: true
      schema:
        type: string
    post:
      summary: register user
      responses:
        '200':
          description: successful
  "/api/v1/login/{username}":
    parameters:
    - name: username
      in: path
      description: username
      required: true
      schema:
        type: string
    get:
      summary: login user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost
