default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Book_An_Appointment_With_A_Doctor_production
  username: postgres
  password: Martial@5009

test:
  <<: *default
  database: Book_An_Appointment_With_A_Doctor_production
  username: postgres
  password: Martial@5009

production:
  <<: *default
  database: Book_An_Appointment_With_A_Doctor_production
  username: Book_An_Appointment_With_A_Doctor_production
  password: <%= ENV["BOOK_AN_APPOINTMENT_WITH_A_DOCTOR"] %>
  adapter: postgresql
